# Generated by Django 5.2.8 on 2025-11-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySummary',
        ),
    ]
