# Generated by Django 5.2.8 on 2025-11-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0004_delete_categorysummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
