# Generated by Django 5.2.8 on 2025-11-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0006_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
