# Generated by Django 5.2.8 on 2025-11-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0008_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
