# Generated by Django 5.2.8 on 2025-12-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0010_category_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total_expense',
        ),
    ]
