# Generated by Django 5.2.8 on 2025-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0011_remove_category_total_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
