# Generated by Django 5.2.8 on 2025-12-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_new', '0013_userprofile'),
    ]

    operations = [
    ]
